### PR TITLE
Fix for OTA file loading response handling.

### PR DESCRIPTION
**Pull request by ISO-B**
Library always failed loading ota file. https://github.com/fairecasoimeme/ZiGate/issues/165

### CODE REVIEW

**Comment by doudz** [comment]
Thanks for this fix

**Comment by Jsl-1** [comment]
Hi @ISO-B 

I have an error at next step (z.ota_image_notify('edf0')) 
Is it related to python lib or zigate or anything else? 

DEBUG:zigate:REQUEST : 0x0500 b'\x02\x00\x00\x0b\xee\xf1\x1e\x01\x00\x008\x00\x00\x11|\x11\x01 \x01\x96#\x00\x02EBL tradfri_control_outlet      \x00\x03\x19\xbe\x00\x00\x00\x00\x00\x03\x19\x80\x00\x02\x8c\xe3\x01'
DEBUG:zigate:Msg to send b'05000048a40200000beef11e010000380000117c110120019623000245424c20747261646672695f636f6e74726f6c5f6f75746c6574202020202020000319be000000000003198000028ce301'
DEBUG:zigate:Encoded Msg to send b'0102150210021048a4021202100210021beef11e0211021002103802100210117c11021120021196230210021245424c20747261646672695f636f6e74726f6c5f6f75746c65742020202020200210021319be0210021002100210021002131980021002128ce3021103'
DEBUG:zigate:Waiting for status message for command 0x0500
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x81\x02\x104\x02\x100\x02\x10\x03\x01\x80\x02\x10\x02\x10\x02\x15\x80\x02\x10\x02\x10\x02\x15\x02\x10\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00340030'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:52, packet_type:48, error:b'', lqi:0
DEBUG:zigate:Received response 0x8000: b'00000500'
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1280, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0030:RESPONSE 0x8000 - Status response : status:0, sequence:52, packet_type:48, error:b'', lqi:0
DEBUG:zigate:Waiting for message 0x8030
DEBUG:zigate:STATUS code to command 0x0500:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1280, error:b'', lqi:0
INFO:zigate:OTA header loaded to server successfully.
DEBUG:zigate:REQUEST : 0x0505 b'\x02\xed\xf0\x01\x01\x00\xff\xff\xff\xff\xff\xff\xff\xffd'
DEBUG:zigate:Msg to send b'0505000f7402edf0010100ffffffffffffffff64'
DEBUG:zigate:Encoded Msg to send b'01021502150210021f740212edf0021102110210ffffffffffffffff6403'
DEBUG:zigate:Waiting for status message for command 0x0505
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x85\x02\x10\x02\x10\x02\x15\x02\x15\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000505'
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1285, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0505:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1285, error:b'', lqi:0

**Comment by ISO-B** [comment]
Is that all that you get? All of those messages seems to have status 0(success). Have you tried to use z.get_ota_status()?

**Comment by Jsl-1** [comment]
Hi,

here is the full  response with get_ota_status() : 

root@jeedom_server:/opt/hassio/homeassistant/ota# python3 ota_update.py
DEBUG:zigate:Try loading persistent file
DEBUG:zigate:Load success
INFO:zigate:Searching ZiGate port
INFO:zigate:ZiGate found at /dev/ttyUSB0
DEBUG:zigate:REQUEST : 0x0010
DEBUG:zigate:Msg to send b'0010000010'
DEBUG:zigate:Encoded Msg to send b'01021010021002101003'
DEBUG:zigate:Waiting for status message for command 0x0010
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x95\x02\x10\x02\x10\x02\x10\x10\x02\x10\x03\x01\x80\x10\x02\x10\x02\x15\x9a\x02\x10\x02\x13\x02\x13\x02\x1f\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000010'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:16, error:b'', lqi:0
DEBUG:zigate:Received response 0x8010: b'0003030f'
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:RESPONSE 0x8010 - Version list : major:3, installer:30f, lqi:0, version:3.0f
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0010:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:16, error:b'', lqi:0
DEBUG:zigate:Waiting for message 0x8010
DEBUG:zigate:Stop waiting, got message 0x8010
DEBUG:zigate:REQUEST : 0x0021 b'\x03\x18\xc8\x00'
DEBUG:zigate:Msg to send b'00210004f60318c800'
DEBUG:zigate:Encoded Msg to send b'0102102102100214f6021318c8021003'
DEBUG:zigate:Waiting for status message for command 0x0021
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\xa4\x02\x10\x02\x10\x02\x10!\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000021'
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:33, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0021:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:33, error:b'', lqi:0
DEBUG:zigate:REQUEST : 0x0023 b'\x00'
DEBUG:zigate:Msg to send b'002300012200'
DEBUG:zigate:Encoded Msg to send b'010210230210021122021003'
DEBUG:zigate:Waiting for status message for command 0x0023
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\xa6\x02\x10\x02\x10\x02\x10#\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000023'
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:35, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0023:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:35, error:b'', lqi:0
DEBUG:zigate:Check network state
DEBUG:zigate:REQUEST : 0x0009
DEBUG:zigate:Msg to send b'0009000009'
DEBUG:zigate:Encoded Msg to send b'010210021902100210021903'
DEBUG:zigate:Waiting for status message for command 0x0009
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x8c\x02\x10\x02\x10\x02\x10\x02\x19\x02\x10\x03\x01\x80\x02\x19\x02\x10\x16\x9f\x02\x10\x02\x10\x02\x10\x15\x8d\x02\x10\x02\x11\xed\xed\x8d\xc6\x1b\xac\x9c\xffh2\x17\xc0\x80\x02\x1b\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000009'
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:9, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8009: b'000000158d0001eded8dc61bac9cff683217c0800b'
DEBUG:zigate:RESPONSE 0x8009 - Network state response : addr:0000, ieee:00158d0001eded8d, panid:50715, extended_panid:12438097093872566400, channel:11, lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0009:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:9, error:b'', lqi:0
DEBUG:zigate:Waiting for message 0x8009
DEBUG:zigate:Stop waiting, got message 0x8009
DEBUG:zigate:Set Zigate Time (firmware >= 3.0f)
DEBUG:zigate:REQUEST : 0x0016 b'$\x12\xda~'
DEBUG:zigate:Msg to send b'00160004802412da7e'
DEBUG:zigate:Encoded Msg to send b'0102101602100214802412da7e03'
DEBUG:zigate:Waiting for status message for command 0x0016
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x93\x02\x10\x02\x10\x02\x10\x16\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000016'
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:22, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0016:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:22, error:b'', lqi:0
DEBUG:zigate:REQUEST : 0x0015
DEBUG:zigate:Msg to send b'0015000015'
DEBUG:zigate:Encoded Msg to send b'01021015021002101503'
DEBUG:zigate:Waiting for status message for command 0x0015
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x90\x02\x10\x02\x10\x02\x10\x15\x02\x10\x03\x01\x80\x15\x02\x10\xebO\x02\x10\x02\x1a\xae\x02\x10\x15\x8d\x02\x10\x02\x12s\x02\x1a\xc3\x02\x10Y\x02\x11\xf1\xa5\x02\x10\x15\x8d\x02\x10\x02\x12s\x9dh\x02\x10p\x02\x12\xbf3\x02\x10\x15\x8d\x02\x10\x02\x12r\xecW\x02\x10\\\x02\x13\xf0%\x02\x10\x15\x8d\x02\x10\x02\x12s\x15\xc5\x02\x10T\x02\x14\x90T\x02\x10\x15\x8d\x02\x10\x02\x12*\xc6T\x02\x10\x8a\x02\x15zb\x02\x10\x15\x8d\x02\x10\x02\x11\xe7Um\x02\x10]\x02\x19)\xe4\x02\x10\x15\x8d\x02\x10\x02\x12*\xc5\x8a\x02\x10|\x02\x1bkJ\x02\x10\x15\x8d\x02\x10\x02\x12\x02\x11\xc7\xb2\x02\x10\xa1(\xfe\x1b\x02\x10\x02\x1do\xff\xfe.\xfe\xdf\x02\x11h)\xed\xf0\x02\x10\x02\x1do\xff\xfe\x9cF\xdf\x02\x11w*\xd7\xd0\x02\x10\x02\x1do\xff\xfe\xa8,V\x02\x11D+z\xd1\x02\x10\x02\x1do\xff\xfe/\xe6I\x02\x11<,\x15\xcf\x02\x10\x02\x1do\xff\xfe\xbb0>\x02\x11B--\x81\x02\x10\x17\x88\x02\x11\x02\x14\x10Xw\x02\x11H.c\x9f\x02\x10\x02\x1do\xff\xfe\xa88K\x02\x11C/\xa1O\x02\x10\x02\x1do\xff\xfe\x9a\x9e\xba\x02\x11Y0\xa6w\x02\x10\x17\x88\x02\x11\x02\x14\xc8\xfeh\x02\x11f1\x02\x14\x02\x10\x02\x10\x02\x1do\xff\xfe\xbe?s\x02\x11M\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000015'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:21, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:Received response 0x8015: b'000aae00158d0002730ac3005901f1a500158d0002739d68007002bf3300158d000272ec57005c03f02500158d00027315c5005404905400158d00022ac654008a057a6200158d0001e7556d005d0929e400158d00022ac58a007c0b6b4a00158d000201c7b200a128fe1b000d6ffffe2efedf016829edf0000d6ffffe9c46df01772ad7d0000d6ffffea82c5601442b7ad1000d6ffffe2fe649013c2c15cf000d6ffffebb303e01422d2d81001788010410587701482e639f000d6ffffea8384b01432fa14f000d6ffffe9a9eba015930a6770017880104c8fe680166310400000d6ffffebe3f73014d'
DEBUG:zigate:RESPONSE 0x8015 - Device list : devices:[OrderedDict([('id', 0), ('addr', '0aae'), ('ieee', '00158d0002730ac3'), ('power_type', 0), ('lqi', 89)]), OrderedDict([('id', 1), ('addr', 'f1a5'), ('ieee', '00158d0002739d68'), ('power_type', 0), ('lqi', 112)]), OrderedDict([('id', 2), ('addr', 'bf33'), ('ieee', '00158d000272ec57'), ('power_type', 0), ('lqi', 92)]), OrderedDict([('id', 3), ('addr', 'f025'), ('ieee', '00158d00027315c5'), ('power_type', 0), ('lqi', 84)]), OrderedDict([('id', 4), ('addr', '9054'), ('ieee', '00158d00022ac654'), ('power_type', 0), ('lqi', 138)]), OrderedDict([('id', 5), ('addr', '7a62'), ('ieee', '00158d0001e7556d'), ('power_type', 0), ('lqi', 93)]), OrderedDict([('id', 9), ('addr', '29e4'), ('ieee', '00158d00022ac58a'), ('power_type', 0), ('lqi', 124)]), OrderedDict([('id', 11), ('addr', '6b4a'), ('ieee', '00158d000201c7b2'), ('power_type', 0), ('lqi', 161)]), OrderedDict([('id', 40), ('addr', 'fe1b'), ('ieee', '000d6ffffe2efedf'), ('power_type', 1), ('lqi', 104)]), OrderedDict([('id', 41), ('addr', 'edf0'), ('ieee', '000d6ffffe9c46df'), ('power_type', 1), ('lqi', 119)]), OrderedDict([('id', 42), ('addr', 'd7d0'), ('ieee', '000d6ffffea82c56'), ('power_type', 1), ('lqi', 68)]), OrderedDict([('id', 43), ('addr', '7ad1'), ('ieee', '000d6ffffe2fe649'), ('power_type', 1), ('lqi', 60)]), OrderedDict([('id', 44), ('addr', '15cf'), ('ieee', '000d6ffffebb303e'), ('power_type', 1), ('lqi', 66)]), OrderedDict([('id', 45), ('addr', '2d81'), ('ieee', '0017880104105877'), ('power_type', 1), ('lqi', 72)]), OrderedDict([('id', 46), ('addr', '639f'), ('ieee', '000d6ffffea8384b'), ('power_type', 1), ('lqi', 67)]), OrderedDict([('id', 47), ('addr', 'a14f'), ('ieee', '000d6ffffe9a9eba'), ('power_type', 1), ('lqi', 89)]), OrderedDict([('id', 48), ('addr', 'a677'), ('ieee', '0017880104c8fe68'), ('power_type', 1), ('lqi', 102)]), OrderedDict([('id', 49), ('addr', '0400'), ('ieee', '000d6ffffebe3f73'), ('power_type', 1), ('lqi', 77)])], lqi:0
DEBUG:zigate:Known devices in zigate : {'7ad1', '2d81', '9054', 'bf33', 'fe1b', '0400', '7a62', '6b4a', '29e4', 'a14f', '15cf', '0aae', '639f', 'd7d0', 'f025', 'f1a5', 'edf0', 'a677'}
DEBUG:zigate:Previous devices missing : set()
DEBUG:zigate:Dispatch ZIGATE_DEVICE_UPDATED
DEBUG:zigate:Dispatch ZIGATE_DEVICE_ADDED
DEBUG:zigate:discover_device f1a5
DEBUG:zigate:no mac_capability
DEBUG:zigate:REQUEST : 0x0042 f1a5
DEBUG:zigate:Msg to send b'0042000214f1a5'
DEBUG:zigate:Encoded Msg to send b'010210420210021214f1a503'
DEBUG:zigate:Waiting for status message for command 0x0042
DEBUG:zigate:STATUS code to command 0x0015:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:21, error:b'', lqi:0
DEBUG:zigate:Waiting for message 0x8015
DEBUG:zigate:Stop waiting, got message 0x8015
DEBUG:zigate:Check Need discovery Device  (0aae) 00158d0002730ac3
WARNING:zigate:No type (modelIdentifier) for device 0aae
DEBUG:zigate:Need discovery : no type
DEBUG:zigate:Need discovery : no endpoints
DEBUG:zigate:Dispatch ZIGATE_DEVICE_NEED_DISCOVERY
DEBUG:zigate:Check Need discovery Device  (f1a5) 00158d0002739d68
WARNING:zigate:No type (modelIdentifier) for device f1a5
DEBUG:zigate:Need discovery : no type
DEBUG:zigate:Need discovery : no endpoints
DEBUG:zigate:Dispatch ZIGATE_DEVICE_NEED_DISCOVERY
DEBUG:zigate:Auto saving /root/.zigate.json
DEBUG:zigate:Saving persistent file
DEBUG:zigate:File already existing, make a backup before
DEBUG:zigate:REQUEST : 0x0500 b'\x02\x00\x00\x0b\xee\xf1\x1e\x01\x00\x008\x00\x00\x11|\x11\x01 \x01\x96#\x00\x02EBL tradfri_control_outlet      \x00\x03\x19\xbe\x00\x00\x00\x00\x00\x03\x19\x80\x00\x02\x8c\xe3\x01'
DEBUG:zigate:Msg to send b'05000048a40200000beef11e010000380000117c110120019623000245424c20747261646672695f636f6e74726f6c5f6f75746c6574202020202020000319be000000000003198000028ce301'
DEBUG:zigate:Encoded Msg to send b'0102150210021048a4021202100210021beef11e0211021002103802100210117c11021120021196230210021245424c20747261646672695f636f6e74726f6c5f6f75746c65742020202020200210021319be0210021002100210021002131980021002128ce3021103'
DEBUG:zigate:Waiting for status message for command 0x0500
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\xff\x02\x108\x02\x10B\x02\x10\x03\x01\x80\x02\x10\x02\x10\x02\x15\x80\x02\x10\x02\x10\x02\x15\x02\x10\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00380042'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:56, packet_type:66, error:b'', lqi:0
DEBUG:zigate:Received response 0x8000: b'00000500'
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1280, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0042:RESPONSE 0x8000 - Status response : status:0, sequence:56, packet_type:66, error:b'', lqi:0
DEBUG:zigate:no endpoints
DEBUG:zigate:REQUEST : 0x0045 f1a5
DEBUG:zigate:Msg to send b'0045000213f1a5'
DEBUG:zigate:Encoded Msg to send b'010210450210021213f1a503'
DEBUG:zigate:Waiting for status message for command 0x0045
DEBUG:zigate:STATUS code to command 0x0500:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1280, error:b'', lqi:0
INFO:zigate:OTA header loaded to server successfully.
DEBUG:zigate:REQUEST : 0x0505 b'\x02\x04\x00\x01\x01\x00\xff\xff\xff\xff\xff\xff\xff\xffd'
DEBUG:zigate:Msg to send b'0505000f6d020400010100ffffffffffffffff64'
DEBUG:zigate:Encoded Msg to send b'01021502150210021f6d021202140210021102110210ffffffffffffffff6403'
DEBUG:zigate:Waiting for status message for command 0x0505
DEBUG:zigate:Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\xf9\x02\x109\x02\x10E\x02\x10\x03\x01\x80\x02\x10\x02\x10\x02\x15\x85\x02\x10\x02\x10\x02\x15\x02\x15\x02\x10\x03'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00390045'
DEBUG:zigate:Dispatch ZIGATE_PACKET_RECEIVED
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:57, packet_type:69, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:Received response 0x8000: b'00000505'
DEBUG:zigate:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1285, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_RESPONSE_RECEIVED
DEBUG:zigate:STATUS code to command 0x0045:RESPONSE 0x8000 - Status response : status:0, sequence:57, packet_type:69, error:b'', lqi:0
DEBUG:zigate:Dispatch ZIGATE_DEVICE_ADDED
DEBUG:zigate:discover_device bf33
DEBUG:zigate:no mac_capability
DEBUG:zigate:REQUEST : 0x0042 bf33
DEBUG:zigate:Msg to send b'00420002ccbf33'
DEBUG:zigate:Encoded Msg to send b'0102104202100212ccbf3303'
DEBUG:zigate:Waiting for status message for command 0x0042
DEBUG:zigate:STATUS code to command 0x0505:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:1285, error:b'', lqi:0
INFO:zigate:OTA process is not active

**Comment by Jsl-1** [comment]
I tried with two different addr, same result.
Here is my python script : 

import logging
import collections
import zigate

logging.basicConfig()
logging.root.setLevel(logging.DEBUG)

import zigate
z = zigate.connect(port=None) # Leave None to auto-discover the port

z.ota_load_image('10005777-3.1-TRADFRI-control-outlet-2.0.019.ota.ota.signed')

z.ota_image_notify('0400')

z.get_ota_status()

**Comment by ISO-B** [comment]
I will test it tomorrow myself. Control outlet is mains power so there shouldn't be need to wake it up by pressing button. It might have updated itself if you loaded ota file to ZiGate earlier and didn't power ZiGate off. Have you checked that it still has old firmware?

**Comment by Jsl-1** [comment]
Ok, thank you for your help.
Don't know how to check version, I will try tomorrow ;)

**Comment by Jsl-1** [comment]
Hi,
Sorry, I didn't find a way to check that it has still old firmware, how can I do that ?

**Comment by Jsl-1** [comment]
You'r right, it's already up to date, i managed to start process by incrementing file version in headers with deconz... 
Sorry and thank you again for your help.

**Pull request merged**
