### PR TITLE
feat: allow template based on endpoint list (with profile and device id)

### PR DESCRIPTION
**Pull request by jBouyoud**
Hello,

My primary devices has no `type` so i can't rely on templeting for discovery. 

This PR allow templating based on `manufactorer_code` and list of endpoints with `device-id`and `profile` of this endpoints.
This doesn't break the current templating on `type` which is the default, but if not available the library will switch on the following templating style.

As I see those informations seems to be always present (for my devices : Ikea Lights, Profalux BSO, Xiaomi sensors)

### CODE REVIEW

**Comment by doudz** [comment]
Could you also provide a template ?

**Comment by jBouyoud** [comment]
Yes of course.  There it is. 
Please note that the last template is based on type attribute (not really on link with this PR intent). 
If you want I can make another PR for that.

**Comment by doudz** [comment]
Looks good, do you use it on prod ?

**Comment by jBouyoud** [comment]
Yes. It works as expected.
Is there anything left to be done before we can merge this PR?

**Pull request merged**
