### PR TITLE
Added support for commands 0x00E0 and 0x00C1

### PR DESCRIPTION
**Pull request by ISO-B**

### CODE REVIEW

**Comment by doudz** [comment]
Looks good !
What's the difference with command 0x0070 ? Just effect ? (really I don't know what's the purpose of 0x0070 and 0x0071)

**Comment by ISO-B** [comment]
Yes it seems that only difference is that you can choose effect. I think that purpose of these identify commands is make possible to identify lights. I only have one bulb at the moment so I know what bulb it is. If you have like 5 lamps on your hallway then it is very handy to use these to identify which is which. I think that all of these identify commands return lamp back to previous state after identify process.

**Comment by doudz** [comment]
So, if it's the same purpose "with effect" I suggest to use the same function and adding an optional effect argument
what do you think about it ?

**Comment by ISO-B** [comment]
I would keep them separate functions since 0x0070 is for all device types and 0x00E0 is only for devices that support ZLL. In my option its easier for user if it is clear what parameters are needed rather than having couple of optional parameters which some are mandatory in some cases and not in other case

**Comment by doudz** [comment]
Thanks !

**Pull request merged**
