### PR TITLE
Added responses for Ikea remote button presses

### PR DESCRIPTION
**Pull request by ISO-B**
Responses for decoding button presses from Ikea 5 button remote

### CODE REVIEW

**Comment by pipiche38** [comment]
@ISO-B I'm not using @doudz library due to the fact that we are implementing a full stack plugin for Domoticz relying on their Framework for Communication and Thread management.

Do you mind @ISO-B and @doudz if we are re-using those responses in our plugin ?

Custom mapping makes really sense. Would be great if we could agree on the format so we all have the possibility to re-use it without too much adaptation .

**Comment by doudz** [comment]
Maybe we could use these responses to update a (fake) multistate cluster 0x0012 ?

**Comment by ISO-B** [comment]
Sure. Some info can be found from https://github.com/fairecasoimeme/ZiGate/issues/6#issuecomment-455944706
```
DEBUG:zigate:RESPONSE 0x8095 - Remote button pressed (ONOFF_UPDATE) : sequence:8, endpoint:1, cluster:6, address_mode:2, addr:4714, cmd:2, rssi:126, button:middle, type:click
DEBUG:zigate:RESPONSE 0x80A7 - Remote button pressed (LEFT/RIGHT) : sequence:9, endpoint:1, cluster:5, address_mode:2, addr:4714, cmd:7, direction:0, additionnal:b'\x01\r\x00', rssi:108, button:right, type:click
DEBUG:zigate:RESPONSE 0x8085 - Remote button pressed (MOVE_TO_LEVEL_UPDATE) : sequence:10, endpoint:1, cluster:8, address_mode:2, addr:4714, cmd:6, rssi:138, button:up, type:click
DEBUG:zigate:RESPONSE 0x80A7 - Remote button pressed (LEFT/RIGHT) : sequence:11, endpoint:1, cluster:5, address_mode:2, addr:4714, cmd:8, direction:0, additionnal:b'\r\x00\xff', rssi:120, button:right, type:hold
DEBUG:zigate:RESPONSE 0x80A7 - Remote button pressed (LEFT/RIGHT) : sequence:16, endpoint:1, cluster:5, address_mode:2, addr:4714, cmd:9, direction:131, additionnal:b'\n\xff\xff', rssi:135, button:previous, type:release
```

Releasing Left or Right button will send release event 5 times since remote sends it 5 times. It's probably to make sure that bulb end scene.

**Comment by ISO-B** [comment]
Made small prototype version of remote remapping. https://github.com/ISO-B/zigate-1/commit/ff44b3cc3cb788e13778d5c06dce336145570195

How that looks? is this even needed anymore?

**Comment by doudz** [comment]
it adds some kind of logic.
This is typically done by home automation system (with Scenario for Jeedom or Automation for Home Assistant, etc) but if you use the lib zigate "alone" you probably need this as convenient tool.

**Comment by ISO-B** [comment]
I was thinking the same thing that most users will do remapping in home automation system. I will develop it bit more so it becomes usable when using zigate "alone". No point to put crazy amounts of time to this. Developing firmware is much better use of time than this "standalone" remapping.

**Comment by doudz** [comment]
I agree
Quick question about Ikea remote, in which case should we put zigate in group 0000 ? or in the same group has the remote ?
What about Ikea motion sensor ?

**Comment by ISO-B** [comment]
I don't know is there any reason related to 5 button remote when it would be required to put zigate to group 0000. I have always put zigate to same group with remote to be able to detect button presses. I don't have motion sensor so can't say anything for that.

**Pull request merged**
